[package]
name = "rttr"
version = "0.1.0"
authors = ["Andreas Kremsner <andreas.kremsner@senacor.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
